project_id = "qsfzelkjsoxukvtuuonl"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://93ff91e2-1a00-4c25-a43c-4626295dad65.lovableproject.com"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_anonymous_sign_ins = false

[functions.gofood-proxy]
verify_jwt = false