// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qsfzelkjsoxukvtuuonl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzZnplbGtqc294dWt2dHV1b25sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2OTMxMzMsImV4cCI6MjA2OTI2OTEzM30.CWZuE8M4VCFZKo9hPx50YYjd4-smwJguhAQCQUveKuw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  realtime: {
    params: {
      eventsPerSecond: 50,
    },
    heartbeatIntervalMs: 15000,
    reconnectAfterMs: (tries: number) => Math.min(tries * 1000, 10000),
    logger: (level, message, details) => {
      console.log(`[Supabase Realtime ${level}]`, message, details);
    },
  },
  global: {
    headers: {
      'x-my-custom-header': 'gofood-group-order',
    },
  },
});